### ISSUE TITLE
Enhance the i18n Ability

### ISSUE THREAD

**Issue by ChengYueJia** [matter-labs/zksync-web-era-docs#100]
In order to help more developer get to know zksync, involves in the eco-system and contribute. Will be beneficial to developers and zksync both to make zksync docs have multiple lang options.

🧾 Expected Behaviour

Have i18n configured in the project, with a contributions guides.
Define the content structure for i18n.

I'm glad to contribute it.

**Comment by ChengYueJia** [comment]
Hi, Guys. I've forked this repo to translate it into Chinese(zk-CN). And polish it on gh-pages. If anyone is Interested. Just pr for it.

The repo is https://github.com/ChengYueJia/zkSync-v2-docs-zh.
The docs is published on https://chengyuejia.github.io/zkSync-v2-docs-zh/dev/developer-guides/hello-world.html.

**Comment by ChengYueJia** [comment]
By the way, I still hope the team of zkSync can enhance the i18n ability for does site. The zkSync should and will be global..

So I'll keep this issue.~

**Comment by 18298822608** [comment]
好的
