### ISSUE TITLE
The navigation of the drop-down menu is transparent and the text overlaps.

### ISSUE THREAD

**Issue by qinjiangban** [matter-labs/zksync-web-era-docs#1092]
The document drop-down menu navigates under a light theme, and the transparent background makes the navigation text overlap with the content text.
![Screenshot_2024-06-07-13-12-56-234_com microsoft emmx](https://github.com/matter-labs/zksync-web-era-docs/assets/95474245/d6a8a889-2e46-4bee-b546-c2a4647bc830)

**Comment by itsacoyote** [comment]
This issue has been fixed.
