### ISSUE TITLE
zkSync rich wallets no longer exist

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/zksync-web-era-docs#1096]
When you run `npx zksync-cli dev start` it gives you a link to the list of private keys and addresses you can use with the local network:

https://docs.zksync.io/docs/tools/testing/era-test-node.html#use-pre-configured-rich-wallets

However, this link no longer exists.

**Comment by PatrickAlphaC** [comment]
This is also broken: https://github.com/zksync-sdk/zksync-ethers/issues/176

**Comment by PatrickAlphaC** [comment]
Main page looks broken too, looks like there might be 2 docs pages still routing? 

<img width="912" alt="Screenshot 2024-06-08 at 8 10 11 PM" src="https://github.com/matter-labs/zksync-web-era-docs/assets/54278053/4f12e010-8b68-4f9a-91ad-9ba78180a95a">

**Comment by PatrickAlphaC** [comment]
Cache cleared fixed the issue on broken images! 

On the rich wallets, I don't understand how that PR fixes the issue though? Where is the list of rich wallets hosted now?

**Comment by uF4No** [comment]
hey @PatrickAlphaC The new version of the `zkcli-in-memory-node` package used in the CLI contains the fix in the rich wallets URL. With `v1.7.2` the rich wallets URL is correct now.

![CleanShot 2024-06-21 at 11 36 45@2x](https://github.com/matter-labs/zksync-web-era-docs/assets/1957117/4dd3cb60-dc82-4025-adec-667680426dbf)

Also, we deployed a fix to help fix the old docs cached version.

**Comment by PatrickAlphaC** [comment]
Confirm fixed. Thank you.
