### ISSUE TITLE
Mismatch on getConfirmedTokens

### ISSUE THREAD

**Issue by defigeneration** [matter-labs/zksync-web-era-docs#252]
https://v2-docs.zksync.io/api/js/providers.html#getconfirmedtokens

here mismatch of _from_ and _start_ variables

they should be unified, which is the ultimate variable number?

**Comment by kailash-manasarovar** [comment]
Hi there, apologies for the delay in responding. We have clarified this function in docs: https://era.zksync.io/docs/api/js/providers.html#getconfirmedtokens. Do let us know if there is anything outstanding. Thanks for raising. Closing.
