### ISSUE TITLE
Outdated EIP-1559 references

### ISSUE THREAD

**Issue by ernestognw** [matter-labs/zksync-web-era-docs#325]
## Description

The troubleshooting docs currently states [EIP-1559 transactions are not yet supported](https://github.com/matter-labs/zksync-web-era-docs/blob/main/docs/dev/troubleshooting/known-issues.md#why-are-metamask-native-contract-interactions-not-working), when [this article](https://blog.matter-labs.io/zksync-2-0-update-dynamic-fees-milestone-completed-c6620a3d2618) announced support for it in August 2022, and also indicated [here](https://era.zksync.io/docs/dev/developer-guides/transactions/transactions.html#transaction-types).

Unfortunately, I think it's the first result that pops up when googling about this. I can send a PR but I want to confirm first if the expected approach would be pointing out that it is an old known issue, and now EIP1559 transactions are supported, or just remove it directly.

**Comment by kailash-manasarovar** [comment]
Thanks for raising this. The whole page needs updating. We will do it asap.
