### ISSUE TITLE
Cannot get the '1EthDefaultBridge, 2EthDefaultBridge' address when i run zks_get_bridge_contracts() - Python SDK

### ISSUE THREAD

**Issue by uninstalls** [matter-labs/zksync-web-era-docs#354]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/94162461/227410954-507b5fb3-1486-4ffb-b1ca-9eb101c5cedc.png">
SDK version: 0.2.0

**Comment by hyperleex** [comment]
same issue

**Comment by MuuJian** [comment]
same issue

**Comment by kailash-manasarovar** [comment]
Hi there, apologies for the inconvenience, we are currently updating the Python SDK. I've added a note to the docs which will be published shortly. Do check back again soon.
