### ISSUE TITLE
no matches found: ethers@^5.7.2

### ISSUE THREAD

**Issue by tonisives** [matter-labs/zksync-web-era-docs#358]
https://github.com/matter-labs/zksync-web-era-docs/blob/5130249955cf49ab29b676d383bc4e8de2675835/docs/api/hardhat/getting-started.md?plain=1#L34

```
➜ yarn init -y && yarn add -D typescript ts-node ethers@^5.7.2 zksync-web3 hardhat @matterlabs/hardhat-zksync-solc @matterlabs/hardhat-zksync-deploy

yarn init v1.22.19
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.04s.
zsh: no matches found: ethers@^5.7.2
```

works with `ethers@5.7.2`. yarn 3.5.0 same error

--

I also had to add these 2 libraries manually:
```
    "@ethersproject/hash": "^5.7.0",
    "@ethersproject/web": "^5.7.1"
```
error was `
Error: zksync-web3 tried to access @ethersproject/web, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
`

**Comment by shreyjay0** [comment]
Works fine on my system, maybe the error is OS/system specific. Could you share the full log? 

I can see from your command input, that @ethersproject/hash and @ethersproject/web are omitted while adding packages, as opposed to the docs command

**Comment by tonisives** [comment]
These 2 libraries are not included here: `https://era.zksync.io/docs/dev/building-on-zksync/hello-world.html#initializing-the-project-deploying-a-smart-contract`

```
# For Yarn
yarn init -y
yarn add -D typescript ts-node ethers@^5.7.2 zksync-web3 hardhat @matterlabs/hardhat-zksync-solc @matterlabs/hardhat-zksync-deploy
```

```
➜ mkdir greeter-example

➜ cd greeter-example

➜ yarn --version
3.5.0

➜ yarn init -y
{
  name: 'greeter-example',
  packageManager: 'yarn@3.5.0'
}

➜ yarn add -D typescript ts-node ethers@^5.7.2 zksync-web3 hardhat @matterlabs/hardhat-zksync-solc @matterlabs/hardhat-zksync-deploy

zsh: no matches found: ethers@^5.7.2
```

**Comment by shreyjay0** [comment]
Yeah, the two libraries are only included in getting started with hardhat's section and not here. Looks like it's not required since things are working as expected. 


I can't reproduce the "no matches found" issue. I've tried on windows and ubuntu with yarn v1.22.19 and it's newer release v3.5.0 and things work smoothly for me. You may try clearing yarn cache or changing terminal.

**Comment by tonisives** [comment]
thanks. I will keep this in mind.
