### ISSUE TITLE
ISSUE: unknown variant `metadata`, expected one of `abi`, `evm.methodIdentifiers`, `storageLayout`, `ast`, `irOptimized`, `evm.legacyAssembly`

### ISSUE THREAD

**Issue by viper7882** [matter-labs/zksync-web-era-docs#394]
Hi,

I'm going through the [Hello World](https://era.zksync.io/docs/dev/building-on-zksync/hello-world.html) example provided with the following environment:
```bash
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

npm -v
9.6.4

yarn --version
3.5.0

npm ls
hello_world@/home/viper7882/hello_world
├── @matterlabs/hardhat-zksync-deploy@0.6.3
├── @matterlabs/hardhat-zksync-solc@0.3.15
├── ethers@5.7.2
├── hardhat@2.13.0
├── ts-node@10.9.1
├── typescript@5.0.3
└── zksync-web3@0.14.3
```

After running `yarn hardhat compile`, the following error is observed:
```bash
yarn hardhat compile
Compiling 1 Solidity file
An unexpected error occurred:

Error: Command failed: /home/viper7882/.cache/hardhat-nodejs/compilers-v2/zksolc/zksolc-v1.3.5 --standard-json    --solc /home/viper7882/.cache/hardhat-nodejs/compilers-v2/linux-amd64/solc-linux-amd64-v0.8.17+commit.8df45f5f
unknown variant `metadata`, expected one of `abi`, `evm.methodIdentifiers`, `storageLayout`, `ast`, `irOptimized`, `evm.legacyAssembly` at line 1 column 593

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/home/viper7882/.cache/hardhat-nodejs/compilers-v2/zksolc/zksolc-v1.3.5 --standard-json    --solc /home/viper7882/.cache/hardhat-nodejs/compilers-v2/linux-amd64/solc-linux-amd64-v0.8.17+commit.8df45f5f'
}
```

I've tried both Ubuntu WSL2 and Windows 10 Powershell, both seems to encounter the same issue. Any idea what have I done incorrectly?

**Comment by withzoo** [comment]
update zksolc to v1.3.8, error disappear, refer to #393

**Comment by kailash-manasarovar** [comment]
Hi there, thanks for the PR. The new instructions for the Quick start should be published in the next 24 hours. Please let us know if you continue to have issues once the doc is updated. Thank you :)

**Comment by viper7882** [comment]
Thanks for the prompt response, @withzoo and @kailash-manasarovar.

I've tried the following commands but none seems to work:
```bash
yarn add -D @matterlabs/hardhat-zksync-solc@^1.3.8
yarn add -D @matterlabs/hardhat-zksync-solc@^v1.3.8
npm i @matterlabs/hardhat-zksync-solc@^1.3.8
npm i @matterlabs/hardhat-zksync-solc@^v1.3.8
```

If it's convenient for you, could you share what's the right approach to update zksolc to v1.3.8?

**Comment by withzoo** [comment]
> 



> Thanks for the prompt response, @withzoo and @kailash-manasarovar.
> 
> I've tried the following commands but none seems to work:
> 
> ```shell
> yarn add -D @matterlabs/hardhat-zksync-solc@^1.3.8
> yarn add -D @matterlabs/hardhat-zksync-solc@^v1.3.8
> npm i @matterlabs/hardhat-zksync-solc@^1.3.8
> npm i @matterlabs/hardhat-zksync-solc@^v1.3.8
> ```
> 
> If it's convenient for you, could you share what's the right approach to update zksolc to v1.3.8?

modify file  'hardhat.config.ts',  set zksolc version to 1.3.8, then execte 'yarn hardhat compile', it works for me

**Comment by viper7882** [comment]
Work like charm. Thanks!
