### ISSUE TITLE
sir not verify 

### ISSUE THREAD

**Issue by Zeshan727964** [matter-labs/zksync-web-era-docs#402]
https://galxe.com/SyncSwap/campaign/GCd81U1awt
sir please chek my link show this notification
1004:If you have fulfilled the requirement, please try 30 seconds later

**Comment by kailash-manasarovar** [comment]
Hi there, I'm going to close this issue for now. Do feel free to raise any issue in our [Discord support channel](https://discord.com/channels/722409280497516566/829103077087772764).
