### ISSUE TITLE
Suggestion for improvement in the faq.md file

### ISSUE THREAD

**Issue by merdan-9** [matter-labs/zksync-web-era-docs#427]
Hi, I was wondering if RSA is a cryptographic precompile, as I can not find this one in other resources.

[faq.md](https://github.com/matter-labs/zksync-web-era-docs/blob/main/docs/dev/troubleshooting/faq.md)
> There are a few other distinctions, for example, gas metering will be different (as is the case for other L2s as well). Some EVM’s cryptographic precompiles (notably pairings and __RSA__) won’t be available in the very first release but will be implemented soon after the launch, with pairing being a priority to allow both Hyperchains and protocols like Aztec/Dark Forest to be deployed without modifications too.

Thank you for your attention to this matter, and I look forward to hearing back from you.

**Comment by kailash-manasarovar** [comment]
Hello, thank you for your question. Perhaps `Address 0x05: Modexp` is what you're looking for?

**Comment by kailash-manasarovar** [comment]
Hello, I'm going to close this ticket for now. Please feel free to reopen if you have doubts @merdan-9 or go ahead and ask a question on our [Discord](https://discord.com/channels/913862762185232435/913862763200249908).
