### ISSUE TITLE
Network in 'hardhat.config' needs to have 'zksync' flag set to 'true'

### ISSUE THREAD

**Issue by dewindtk** [matter-labs/zksync-web-era-docs#447]
Hi. I am currently writing a script which would deploy a Contract on the zksync Era mainnet, however "'@matterlabs/hardhat-zksync-deploy" is giving me the above error, although I have the flag set to true.

What could have went wrong?

Thanks in advance.

**Comment by githubdoramon** [comment]
@dewindtk can you share your full hardhat config file pls?

**Comment by Edgars112233** [comment]
> Hi. I am currently writing a script which would deploy a Contract on the zksync Era mainnet, however "'@matterlabs/hardhat-zksync-deploy" is giving me the above error, although I have the flag set to true.
> 
> 
> 
> What could have went wrong?
> 
> 
> 
> Thanks in advance.

**Comment by kailash-manasarovar** [comment]
Hi there @dewindtk we don't have enough information from you to understand what is going on if you are still having trouble. Please send us your code, including your hardhat config, and we can give you a hand.

**Comment by kailash-manasarovar** [comment]
Hi there @dewindtk since you didn't get back to us here yet, I hope you managed to resolve your issue. If not, I recommend contacting our support team: https://era.zksync.io/docs/contact.html#user-community-and-support. As always, thanks for reaching out and I'm closing this issue for now.
