### ISSUE TITLE
Not so clear on where do you store the bytecode

### ISSUE THREAD

**Issue by GopherJ** [matter-labs/zksync-web-era-docs#593]
Reading https://era.zksync.io/docs/dev/building-on-zksync/contracts/contract-deployment.html#note-on-factory-deps, the doc says the preimages of bytecode hashes are revealed on L1, and then it says that zksync doesn't store bytecode but only bytecode hash. So the question is:

> where is the bytecode stored exactly?

1) do you fetch them from L1? (which requires running L1 node together with L2 node, then the doc needs to be improved)
2) do you still store them on L2? then the doc needs to be modified

**Comment by kailash-manasarovar** [comment]
Hi @GopherJ this doc is scheduled for a complete overhaul in due course. We're aware of the problems with some of the content in this section. Please keep your eye out for the updates. Thank you.
