### ISSUE TITLE
Error code description

### ISSUE THREAD

**Issue by GopherJ** [matter-labs/zksync-web-era-docs#599]
I got something error log like the following, it's very vague and can the doc describe on how to debug such error?

[error.log](https://github.com/matter-labs/zksync-web-era-docs/files/11752510/error.log)

TxHash:  https://goerli.explorer.zksync.io/tx/0xd76558667b995853bb496e8e523d637763d4e58914892ff949649b160ccbb2df

**Comment by kailash-manasarovar** [comment]
Hi @GopherJ thank you for raising. We have a ticket for the docs team open to document all backend errors so please keep an eye out for the update.
