### ISSUE TITLE
how to get all the transactions?

### ISSUE THREAD

**Issue by viponedream** [matter-labs/zksync-web-era-docs#661]
https://explorer.zksync.io/transactions/
no api to get transactions?

**Comment by Ocg75** [comment]
Hello;

Though my transation from Era to ETH wallet seems "executed" i can no see my tasction amount in the wallet.

I  will be happy if you could check it out for me please: 

https://explorer.zksync.io/tx/0xecff57959a71114efa8a22cd354a2d1292afe43895dba76c41416116c7f01193

[zkSync Era Block Explorer](https://explorer.zksync.io/tx/0xecff57959a71114efa8a22cd354a2d1292afe43895dba76c41416116c7f01193)
zkSync Era Block Explorer provides all the information to deep dive into transactions, blocks, contracts, and much more. Deep dive into zkSync Era and explore the network.
explorer.zksync.io


https://etherscan.io/address/0x76B5aE1BbD4843F6F0bB1CEdB4Efccc620AfAF86

Thanks,

**Comment by cklat** [comment]
I'm wondering this question myself these days...
on the lite network there is a dedicated endpoint to get all the transaction for an account but it seems there 's none for the era network.. ? 

Is there a way to get all the accounts' transactions more or less hassle-free? 

To be honest, I find a bit strange for such a popular not to have an explorer where you can at least csv export your transcations.

Appreciate any help! Thanks!

**Comment by dutterbutter** [comment]
Please direct these questions to the developer discussion pages 👉 https://github.com/zkSync-Community-Hub/zkync-developers/discussions
