### ISSUE TITLE
next / previous page links are incorrect for first page of a section

### ISSUE THREAD

**Issue by sebastiantf** [matter-labs/zksync-web-era-docs#721]
Eg.:
https://era.zksync.io/docs/reference/concepts/rollups.html#what-are-optimistic-rollups has next page pointing to Architecture when it should be zkSync Era Basics

<img width="1257" alt="Screenshot 2023-09-27 at 10 22 17 AM" src="https://github.com/matter-labs/zksync-web-era-docs/assets/36922376/c5ff3b18-ed33-4a8c-9445-c221b8dcb391">

Same with the first page of Architecture and so on

Might be related: https://github.com/vuejs/vuepress/issues/1327

**Comment by vamsi4845** [comment]
I would like to work on this
