### ISSUE TITLE
Getting error while compiling contract provided in template of documentation [greeter example]

### ISSUE THREAD

**Issue by Anjan-poudel-1** [matter-labs/zksync-web-era-docs#842]
![image](https://github.com/matter-labs/zksync-web-era-docs/assets/59379481/3170e5ab-1e87-40aa-a81c-2cf2e3a470aa)

**Comment by Damkols** [comment]
Hello @Anjan-poudel-1 I would love to work on this task, can you kindly assign the task to me.
