### ISSUE TITLE
Update deposit/withdraw how-to guides with zksync-ethers

### ISSUE THREAD

**Issue by uF4No** [matter-labs/zksync-web-era-docs#844]
The How to guides to deposit and withdraw ETH and ERC20 tokens use the deprecated library `zksync-web3`. These should be update to use `zksync-ethers`.

**Comment by yash251** [comment]
Please assign me this issue @uF4No

**Comment by Deepak2030** [comment]
Hey @uF4No can I work on this?
Also, can you share the link to the documentation where the change is needed? I'm not able to find it in the how-to directory

**Comment by bobeu** [comment]
@uF4No, I'd like to work on this if still open.

**Comment by cgrade** [comment]
Hi @uF4No can you kindly assign this to me, I'd love to work on this if it's still open

**Comment by Damkols** [comment]
Hello @uF4No i would like to work on this, can kindly assign this to me

**Comment by vamsi4845** [comment]
hey @uF4No  i would like to work on this
