### ISSUE TITLE
Multi language needed

### ISSUE THREAD

**Issue by Speedevs** [matter-labs/zksync-web-era-docs#916]
<img width="1038" alt="image" src="https://github.com/matter-labs/zksync-web-era-docs/assets/45816964/fc84d336-657e-48eb-a790-9a7961ae8c25">

More multi language needed in the explorer

https://explorer.zksync.io/ (like CN)

**Comment by mahmutt301** [comment]
Dünyada farklı dillerde konuşan milyonlarca insanı düşünürsek çoklu dil elzem bir durum.

**Comment by jagadbumi1000** [comment]
Indonesia language would be great

**Comment by Speedevs** [comment]
Yeah that's what am telling the team .

**Comment by mahmutt301** [comment]
good idea

**Comment by AlexioMu** [comment]
Dutch - I can help with the translation

**Comment by Speedevs** [comment]
Hope team approves it .
We really need it

**Comment by SSJMUNDEN2** [comment]
German would be also a great option thanks

**Comment by Speedevs** [comment]
Yeah literally.
I guess team assume many things 🫠

**Comment by Speedevs** [comment]
Hope they put this in consideration

**Comment by dhimbirazi** [comment]
there's no arabic content, I think it will great if you add arabic language also some video tutorial

**Comment by Speedevs** [comment]
> there's no arabic content, I think it will great if you add arabic language also some video tutorial

Me too .
Hope team put this in consideration
