### ISSUE TITLE
Document description is incomplete

### ISSUE THREAD

**Issue by jashyang** [matter-labs/zksync-web-era-docs#969]
In the `Getting Started` documentation of `Hardhat Plugins`, under the `Prerequisites` section, the third item has an incomplete language.

The current text is
`If not, please refer to the first section of the`,
and I think it may be
`If not, please refer to the first section of the Quickstart`.  or Others...

link: `https://docs.zksync.io/build/tooling/hardhat/hardhat-zksync-solc.html`

![image](https://github.com/matter-labs/zksync-web-era-docs/assets/26290961/16b6f769-60c9-4158-975b-7f5a0398bd67)

**Comment by moset5820** [comment]
so
